# Form implementation generated from reading ui file 'TranslateMate.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 520)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 520))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 16777215))
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("* {\n"
"   background-color: #b8b6b6;\n"
"   font: Fira Sans Condensed;     \n"
"}\n"
"QScrollBar {\n"
"    border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #f4f4f5;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #d0d0d0;\n"
"    min-height: 0px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: -10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height:  -10 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.Grid = QtWidgets.QWidget(parent=MainWindow)
        self.Grid.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Grid.setObjectName("Grid")
        self.TranslateWindow = ClickableLabel(parent=self.Grid)
        self.TranslateWindow.setGeometry(QtCore.QRect(10, 60, 40, 40))
        self.TranslateWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.TranslateWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.TranslateWindow.setAutoFillBackground(False)
        self.TranslateWindow.setStyleSheet("")
        self.TranslateWindow.setText("")
        self.TranslateWindow.setPixmap(QtGui.QPixmap("img/translation.png"))
        self.TranslateWindow.setScaledContents(True)
        self.TranslateWindow.setObjectName("TranslateWindow")
        self.DisplayArea = QtWidgets.QStackedWidget(parent=self.Grid)
        self.DisplayArea.setGeometry(QtCore.QRect(50, 0, 1100, 520))
        self.DisplayArea.setMaximumSize(QtCore.QSize(1100, 16777215))
        self.DisplayArea.setObjectName("DisplayArea")
        self.Translate = QtWidgets.QWidget()
        self.Translate.setMaximumSize(QtCore.QSize(1100, 16777215))
        self.Translate.setObjectName("Translate")
        self.inputBox = QtWidgets.QTextEdit(parent=self.Translate)
        self.inputBox.setGeometry(QtCore.QRect(20, 50, 500, 380))
        self.inputBox.setStyleSheet("border: 1px solid black;\n"
"border-radius: 10px 10px;\n"
"background: #f4f4f5;\n"
"font-size: 16px;\n"
"color:black;")
        self.inputBox.setObjectName("inputBox")
        self.translateBox = QtWidgets.QTextEdit(parent=self.Translate)
        self.translateBox.setEnabled(True)
        self.translateBox.setGeometry(QtCore.QRect(530, 50, 500, 380))
        self.translateBox.setStyleSheet("border: 1px solid black;\n"
"border-radius: 10px;\n"
"background: #f4f4f5;\n"
"font-size: 16px;\n"
"color:black;")
        self.translateBox.setReadOnly(True)
        self.translateBox.setObjectName("translateBox")
        self.cleanTranslate = ClickableLabel(parent=self.Translate)
        self.cleanTranslate.setEnabled(False)
        self.cleanTranslate.setGeometry(QtCore.QRect(470, 60, 30, 30))
        self.cleanTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cleanTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.cleanTranslate.setAutoFillBackground(False)
        self.cleanTranslate.setStyleSheet("#cleanTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    background: none;\n"
"    opacity: 0.5;\n"
"    padding: 7px;\n"
"}\n"
"#cleanTranslate:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.cleanTranslate.setText("")
        self.cleanTranslate.setPixmap(QtGui.QPixmap("img/close.png"))
        self.cleanTranslate.setScaledContents(True)
        self.cleanTranslate.setObjectName("cleanTranslate")
        self.sourceLangList = QtWidgets.QComboBox(parent=self.Translate)
        self.sourceLangList.setGeometry(QtCore.QRect(30, 10, 200, 30))
        self.sourceLangList.setStyleSheet("#sourceLangList {\n"
"    font: 11pt Fira Sans Condensed;     \n"
"    background-color: #2e2e2e;\n"
"    border-top: 0px solid #3e3e3e;\n"
"    border-left: 0px solid #3e3e3e;\n"
"    border-right: 0px solid #3e3e3e;\n"
"    border-bottom: 2px solid #3e3e3e;\n"
"    padding: 5%;\n"
"    max-height: 30px;\n"
"    min-width: 140px;\n"
"    color: white;\n"
"    selection-background-color: #5e5e5e;\n"
"    border-radius: 2px;\n"
"}\n"
"#sourceLangList:drop-down {\n"
"    border: none;\n"
"}\n"
"#sourceLangList:down-arrow {\n"
"    image: url(img/downButton.png);\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-width: 0px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#sourceLangList:pressed {\n"
"    position: relative;\n"
"    top: 1px; left: 1px;\n"
"}")
        self.sourceLangList.setEditable(True)
        self.sourceLangList.setObjectName("sourceLangList")
        self.reverseTranslate = ClickableLabel(parent=self.Translate)
        self.reverseTranslate.setGeometry(QtCore.QRect(510, 10, 30, 30))
        self.reverseTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reverseTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.reverseTranslate.setAutoFillBackground(False)
        self.reverseTranslate.setStyleSheet("#reverseTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"}\n"
"#reverseTranslate:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.reverseTranslate.setText("")
        self.reverseTranslate.setPixmap(QtGui.QPixmap("img/reverseTranslate.png"))
        self.reverseTranslate.setScaledContents(True)
        self.reverseTranslate.setObjectName("reverseTranslate")
        self.targetLangList = QtWidgets.QComboBox(parent=self.Translate)
        self.targetLangList.setGeometry(QtCore.QRect(820, 10, 200, 30))
        self.targetLangList.setStyleSheet("#targetLangList {\n"
"    font: 11pt Fira Sans Condensed;     \n"
"    background-color: #2e2e2e;\n"
"    border-top: 0px solid #3e3e3e;\n"
"    border-left: 0px solid #3e3e3e;\n"
"    border-right: 0px solid #3e3e3e;\n"
"    border-bottom: 2px solid #3e3e3e;\n"
"    padding: 5%;\n"
"    max-height: 30px;\n"
"    min-width: 140px;\n"
"    color: white;\n"
"    selection-background-color: #5e5e5e;\n"
"    border-radius: 2px;\n"
"}\n"
"#targetLangList:drop-down {\n"
"    border: none;\n"
"}\n"
"#targetLangList:down-arrow {\n"
"    image: url(img/downButton.png);\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-width: 0px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#targetLangList:pressed {\n"
"    position: relative;\n"
"    top: 1px; left: 1px;\n"
"}")
        self.targetLangList.setEditable(True)
        self.targetLangList.setObjectName("targetLangList")
        self.RightPanel = QtWidgets.QWidget(parent=self.Translate)
        self.RightPanel.setGeometry(QtCore.QRect(530, 430, 490, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightPanel.sizePolicy().hasHeightForWidth())
        self.RightPanel.setSizePolicy(sizePolicy)
        self.RightPanel.setMinimumSize(QtCore.QSize(490, 50))
        self.RightPanel.setMaximumSize(QtCore.QSize(490, 40))
        self.RightPanel.setBaseSize(QtCore.QSize(490, 40))
        self.RightPanel.setStyleSheet("")
        self.RightPanel.setObjectName("RightPanel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.RightPanel)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, -10, 491, 471))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.rightPanelLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.rightPanelLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.rightPanelLayout.setContentsMargins(10, 5, 0, 0)
        self.rightPanelLayout.setSpacing(6)
        self.rightPanelLayout.setObjectName("rightPanelLayout")
        self.pronunciation = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.pronunciation.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pronunciation.sizePolicy().hasHeightForWidth())
        self.pronunciation.setSizePolicy(sizePolicy)
        self.pronunciation.setMinimumSize(QtCore.QSize(35, 35))
        self.pronunciation.setMaximumSize(QtCore.QSize(35, 35))
        self.pronunciation.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pronunciation.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pronunciation.setAutoFillBackground(False)
        self.pronunciation.setStyleSheet("")
        self.pronunciation.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.pronunciation.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.pronunciation.setText("")
        self.pronunciation.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.pronunciation.setPixmap(QtGui.QPixmap("img/pronunciation.png"))
        self.pronunciation.setScaledContents(True)
        self.pronunciation.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pronunciation.setOpenExternalLinks(False)
        self.pronunciation.setObjectName("pronunciation")
        self.rightPanelLayout.addWidget(self.pronunciation, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.copyTranslate = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.copyTranslate.setEnabled(False)
        self.copyTranslate.setMaximumSize(QtCore.QSize(35, 35))
        self.copyTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.copyTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.copyTranslate.setAutoFillBackground(False)
        self.copyTranslate.setStyleSheet("")
        self.copyTranslate.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.copyTranslate.setText("")
        self.copyTranslate.setPixmap(QtGui.QPixmap("img/copy.png"))
        self.copyTranslate.setScaledContents(True)
        self.copyTranslate.setObjectName("copyTranslate")
        self.rightPanelLayout.addWidget(self.copyTranslate, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.saveTranslatedText = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.saveTranslatedText.setEnabled(False)
        self.saveTranslatedText.setMinimumSize(QtCore.QSize(35, 35))
        self.saveTranslatedText.setMaximumSize(QtCore.QSize(35, 35))
        self.saveTranslatedText.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.saveTranslatedText.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.saveTranslatedText.setAutoFillBackground(False)
        self.saveTranslatedText.setStyleSheet("")
        self.saveTranslatedText.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.saveTranslatedText.setText("")
        self.saveTranslatedText.setPixmap(QtGui.QPixmap("img/saveTranslatedText.png"))
        self.saveTranslatedText.setScaledContents(True)
        self.saveTranslatedText.setObjectName("saveTranslatedText")
        self.rightPanelLayout.addWidget(self.saveTranslatedText, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.LeftPanel = QtWidgets.QWidget(parent=self.Translate)
        self.LeftPanel.setEnabled(True)
        self.LeftPanel.setGeometry(QtCore.QRect(20, 430, 490, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftPanel.sizePolicy().hasHeightForWidth())
        self.LeftPanel.setSizePolicy(sizePolicy)
        self.LeftPanel.setMinimumSize(QtCore.QSize(490, 50))
        self.LeftPanel.setMaximumSize(QtCore.QSize(490, 40))
        self.LeftPanel.setBaseSize(QtCore.QSize(490, 40))
        self.LeftPanel.setStyleSheet("")
        self.LeftPanel.setObjectName("LeftPanel")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.LeftPanel)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, -10, 491, 471))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.leftPanelLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.leftPanelLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.leftPanelLayout.setContentsMargins(10, 5, 0, 0)
        self.leftPanelLayout.setSpacing(6)
        self.leftPanelLayout.setObjectName("leftPanelLayout")
        self.pastSourceText = ClickableLabel(parent=self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pastSourceText.sizePolicy().hasHeightForWidth())
        self.pastSourceText.setSizePolicy(sizePolicy)
        self.pastSourceText.setMinimumSize(QtCore.QSize(35, 35))
        self.pastSourceText.setMaximumSize(QtCore.QSize(35, 35))
        self.pastSourceText.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pastSourceText.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pastSourceText.setAutoFillBackground(False)
        self.pastSourceText.setStyleSheet("")
        self.pastSourceText.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.pastSourceText.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.pastSourceText.setText("")
        self.pastSourceText.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.pastSourceText.setPixmap(QtGui.QPixmap("img/paste.png"))
        self.pastSourceText.setScaledContents(True)
        self.pastSourceText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pastSourceText.setOpenExternalLinks(False)
        self.pastSourceText.setObjectName("pastSourceText")
        self.leftPanelLayout.addWidget(self.pastSourceText, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.microphone = ClickableLabel(parent=self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.microphone.sizePolicy().hasHeightForWidth())
        self.microphone.setSizePolicy(sizePolicy)
        self.microphone.setMinimumSize(QtCore.QSize(35, 35))
        self.microphone.setMaximumSize(QtCore.QSize(35, 35))
        self.microphone.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.microphone.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.microphone.setAutoFillBackground(False)
        self.microphone.setStyleSheet("")
        self.microphone.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.microphone.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.microphone.setText("")
        self.microphone.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.microphone.setPixmap(QtGui.QPixmap("img/microphone.png"))
        self.microphone.setScaledContents(True)
        self.microphone.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.microphone.setOpenExternalLinks(False)
        self.microphone.setObjectName("microphone")
        self.leftPanelLayout.addWidget(self.microphone, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.sourcePronunciation = ClickableLabel(parent=self.horizontalLayoutWidget_3)
        self.sourcePronunciation.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourcePronunciation.sizePolicy().hasHeightForWidth())
        self.sourcePronunciation.setSizePolicy(sizePolicy)
        self.sourcePronunciation.setMinimumSize(QtCore.QSize(35, 35))
        self.sourcePronunciation.setMaximumSize(QtCore.QSize(35, 35))
        self.sourcePronunciation.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sourcePronunciation.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.sourcePronunciation.setAutoFillBackground(False)
        self.sourcePronunciation.setStyleSheet("")
        self.sourcePronunciation.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.sourcePronunciation.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.sourcePronunciation.setText("")
        self.sourcePronunciation.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.sourcePronunciation.setPixmap(QtGui.QPixmap("img/pronunciation.png"))
        self.sourcePronunciation.setScaledContents(True)
        self.sourcePronunciation.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.sourcePronunciation.setOpenExternalLinks(False)
        self.sourcePronunciation.setObjectName("sourcePronunciation")
        self.leftPanelLayout.addWidget(self.sourcePronunciation, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.sourceCopyTranslate = ClickableLabel(parent=self.horizontalLayoutWidget_3)
        self.sourceCopyTranslate.setEnabled(False)
        self.sourceCopyTranslate.setMaximumSize(QtCore.QSize(35, 35))
        self.sourceCopyTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sourceCopyTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.sourceCopyTranslate.setAutoFillBackground(False)
        self.sourceCopyTranslate.setStyleSheet("")
        self.sourceCopyTranslate.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.sourceCopyTranslate.setText("")
        self.sourceCopyTranslate.setPixmap(QtGui.QPixmap("img/copy.png"))
        self.sourceCopyTranslate.setScaledContents(True)
        self.sourceCopyTranslate.setObjectName("sourceCopyTranslate")
        self.leftPanelLayout.addWidget(self.sourceCopyTranslate, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.charCounter = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.charCounter.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charCounter.sizePolicy().hasHeightForWidth())
        self.charCounter.setSizePolicy(sizePolicy)
        self.charCounter.setMinimumSize(QtCore.QSize(170, 0))
        self.charCounter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.charCounter.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.charCounter.setLineWidth(2)
        self.charCounter.setScaledContents(False)
        self.charCounter.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.charCounter.setObjectName("charCounter")
        self.leftPanelLayout.addWidget(self.charCounter, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.prevTranslate = ClickableLabel(parent=self.Translate)
        self.prevTranslate.setEnabled(False)
        self.prevTranslate.setGeometry(QtCore.QRect(470, 10, 30, 30))
        self.prevTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.prevTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.prevTranslate.setAutoFillBackground(False)
        self.prevTranslate.setStyleSheet("#prevTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"}\n"
"#prevTranslate:hover  {\n"
"    background: #fff6f7;\n"
"}\n"
"#prevTranslate:disabled  {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.prevTranslate.setText("")
        self.prevTranslate.setPixmap(QtGui.QPixmap("img/arrow_left.png"))
        self.prevTranslate.setScaledContents(True)
        self.prevTranslate.setObjectName("prevTranslate")
        self.nextTranslate = ClickableLabel(parent=self.Translate)
        self.nextTranslate.setEnabled(False)
        self.nextTranslate.setGeometry(QtCore.QRect(550, 10, 30, 30))
        self.nextTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.nextTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.nextTranslate.setAutoFillBackground(False)
        self.nextTranslate.setStyleSheet("#nextTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"}\n"
"#nextTranslate:hover  {\n"
"    background:  #fff6f7;\n"
"}\n"
"#nextTranslate:disabled  {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.nextTranslate.setText("")
        self.nextTranslate.setPixmap(QtGui.QPixmap("img/arrow_right.png"))
        self.nextTranslate.setScaledContents(True)
        self.nextTranslate.setObjectName("nextTranslate")
        self.DisplayArea.addWidget(self.Translate)
        self.TranslationView = QtWidgets.QWidget()
        self.TranslationView.setObjectName("TranslationView")
        self.TranslationTableWidget = QtWidgets.QTableView(parent=self.TranslationView)
        self.TranslationTableWidget.setGeometry(QtCore.QRect(20, 0, 1021, 441))
        self.TranslationTableWidget.setStyleSheet("QTableWidget {\n"
"    border: transparent;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background: #fff5e0;\n"
"    color: #000000;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QTableWidget::item:focus\n"
"{\n"
"   background-color: #b8b6b6; \n"
"    background: #b8b6b6;\n"
"   selection-background-color: #b8b6b6;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    border-radius: 3px;\n"
"    text-align: center;\n"
"    font-weight: bold;\n"
"    spacing: 1px;\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #676767;\n"
"    font-size:12px;\n"
"}")
        self.TranslationTableWidget.setObjectName("TranslationTableWidget")
        self.DisplayArea.addWidget(self.TranslationView)
        self.FlashCards = QtWidgets.QWidget()
        self.FlashCards.setObjectName("FlashCards")
        self.cardWidget = QtWidgets.QStackedWidget(parent=self.FlashCards)
        self.cardWidget.setGeometry(QtCore.QRect(40, 60, 200, 151))
        self.cardWidget.setObjectName("cardWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.cardTextObj = QtWidgets.QPlainTextEdit(parent=self.page)
        self.cardTextObj.setGeometry(QtCore.QRect(3, 10, 191, 141))
        self.cardTextObj.setPlainText("")
        self.cardTextObj.setObjectName("cardTextObj")
        self.cardWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.cardWidget.addWidget(self.page_2)
        self.flashCardCansel = QtWidgets.QLabel(parent=self.FlashCards)
        self.flashCardCansel.setGeometry(QtCore.QRect(90, 230, 40, 40))
        self.flashCardCansel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.flashCardCansel.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.flashCardCansel.setAutoFillBackground(False)
        self.flashCardCansel.setStyleSheet("#flashCardsWindow {\n"
"    background-repeat: no-repeat;\n"
"    border-radius:  5px;\n"
"}\n"
"#flashCardsWindow:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.flashCardCansel.setText("")
        self.flashCardCansel.setPixmap(QtGui.QPixmap("img/cansel.png"))
        self.flashCardCansel.setScaledContents(True)
        self.flashCardCansel.setObjectName("flashCardCansel")
        self.flashCardOk = QtWidgets.QLabel(parent=self.FlashCards)
        self.flashCardOk.setGeometry(QtCore.QRect(130, 230, 40, 40))
        self.flashCardOk.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.flashCardOk.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.flashCardOk.setAutoFillBackground(False)
        self.flashCardOk.setStyleSheet("#flashCardsWindow {\n"
"    background-repeat: no-repeat;\n"
"    border-radius:  5px;\n"
"}\n"
"#flashCardsWindow:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.flashCardOk.setText("")
        self.flashCardOk.setPixmap(QtGui.QPixmap("img/ok.png"))
        self.flashCardOk.setScaledContents(True)
        self.flashCardOk.setObjectName("flashCardOk")
        self.DisplayArea.addWidget(self.FlashCards)
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.settingsTabWidget = QtWidgets.QTabWidget(parent=self.Settings)
        self.settingsTabWidget.setGeometry(QtCore.QRect(16, -1, 1031, 481))
        font = QtGui.QFont()
        font.setFamily("Sans Condensed")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.settingsTabWidget.setFont(font)
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.generalScrollArea = QtWidgets.QScrollArea(parent=self.generalTab)
        self.generalScrollArea.setGeometry(QtCore.QRect(-1, -1, 1021, 431))
        self.generalScrollArea.setWidgetResizable(True)
        self.generalScrollArea.setObjectName("generalScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1019, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1021, 441))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.defaultTranslatorLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.defaultTranslatorLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.defaultTranslatorLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.defaultTranslatorLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.defaultTranslatorLabel.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.defaultTranslatorLabel.setScaledContents(True)
        self.defaultTranslatorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.defaultTranslatorLabel.setWordWrap(False)
        self.defaultTranslatorLabel.setObjectName("defaultTranslatorLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.defaultTranslatorLabel)
        self.defaultTranslatorComboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.defaultTranslatorComboBox.setObjectName("defaultTranslatorComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.defaultTranslatorComboBox)
        self.generalScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.settingsTabWidget.addTab(self.generalTab, "")
        self.translateTab = QtWidgets.QWidget()
        self.translateTab.setObjectName("translateTab")
        self.settingsTabWidget.addTab(self.translateTab, "")
        self.DisplayArea.addWidget(self.Settings)
        self.TranslationViewWindow = ClickableLabel(parent=self.Grid)
        self.TranslationViewWindow.setGeometry(QtCore.QRect(10, 110, 40, 40))
        self.TranslationViewWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.TranslationViewWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.TranslationViewWindow.setAutoFillBackground(False)
        self.TranslationViewWindow.setStyleSheet("")
        self.TranslationViewWindow.setText("")
        self.TranslationViewWindow.setPixmap(QtGui.QPixmap("img/saveButton.png"))
        self.TranslationViewWindow.setScaledContents(True)
        self.TranslationViewWindow.setObjectName("TranslationViewWindow")
        self.FlashCardsWindow = ClickableLabel(parent=self.Grid)
        self.FlashCardsWindow.setGeometry(QtCore.QRect(10, 160, 40, 40))
        self.FlashCardsWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.FlashCardsWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.FlashCardsWindow.setAutoFillBackground(False)
        self.FlashCardsWindow.setStyleSheet("")
        self.FlashCardsWindow.setText("")
        self.FlashCardsWindow.setPixmap(QtGui.QPixmap("img/flashCards.png"))
        self.FlashCardsWindow.setScaledContents(True)
        self.FlashCardsWindow.setObjectName("FlashCardsWindow")
        self.SettingsWindow = ClickableLabel(parent=self.Grid)
        self.SettingsWindow.setGeometry(QtCore.QRect(10, 370, 40, 40))
        self.SettingsWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SettingsWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.SettingsWindow.setAutoFillBackground(False)
        self.SettingsWindow.setStyleSheet("")
        self.SettingsWindow.setText("")
        self.SettingsWindow.setPixmap(QtGui.QPixmap("img/settings.png"))
        self.SettingsWindow.setScaledContents(True)
        self.SettingsWindow.setObjectName("SettingsWindow")
        MainWindow.setCentralWidget(self.Grid)
        self.MenuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 1100, 20))
        self.MenuBar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.MenuBar.setAutoFillBackground(False)
        self.MenuBar.setStyleSheet("#MenuBar {\n"
"    background: black;\n"
"    color: white;\n"
"}\n"
"")
        self.MenuBar.setObjectName("MenuBar")
        self.Menu = QtWidgets.QMenu(parent=self.MenuBar)
        self.Menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Menu.setStyleSheet("background-color: #2e2e2e;")
        self.Menu.setObjectName("Menu")
        self.MenuTranslate = QtWidgets.QMenu(parent=self.MenuBar)
        self.MenuTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MenuTranslate.setStyleSheet("background-color: #2e2e2e;")
        self.MenuTranslate.setObjectName("MenuTranslate")
        self.chooseTranslator = QtWidgets.QMenu(parent=self.MenuTranslate)
        self.chooseTranslator.setStyleSheet("")
        self.chooseTranslator.setObjectName("chooseTranslator")
        self.MenuProunanciation = QtWidgets.QMenu(parent=self.MenuBar)
        self.MenuProunanciation.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MenuProunanciation.setStyleSheet("background-color: #2e2e2e;")
        self.MenuProunanciation.setObjectName("MenuProunanciation")
        self.MenuType = QtWidgets.QMenu(parent=self.MenuProunanciation)
        self.MenuType.setObjectName("MenuType")
        MainWindow.setMenuBar(self.MenuBar)
        self.StatusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.StatusBar.setObjectName("StatusBar")
        MainWindow.setStatusBar(self.StatusBar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setShortcutVisibleInContextMenu(False)
        self.actionExit.setObjectName("actionExit")
        self.actionGoogleTranslator = QtGui.QAction(parent=MainWindow)
        self.actionGoogleTranslator.setCheckable(True)
        self.actionGoogleTranslator.setChecked(True)
        self.actionGoogleTranslator.setObjectName("actionGoogleTranslator")
        self.actionLeaveTheFormatting = QtGui.QAction(parent=MainWindow)
        self.actionLeaveTheFormatting.setCheckable(True)
        self.actionLeaveTheFormatting.setObjectName("actionLeaveTheFormatting")
        self.actionDeeplTranslator = QtGui.QAction(parent=MainWindow)
        self.actionDeeplTranslator.setCheckable(True)
        self.actionDeeplTranslator.setChecked(False)
        self.actionDeeplTranslator.setObjectName("actionDeeplTranslator")
        self.actionPyttsx = QtGui.QAction(parent=MainWindow)
        self.actionPyttsx.setCheckable(True)
        self.actionPyttsx.setChecked(True)
        self.actionPyttsx.setObjectName("actionPyttsx")
        self.Menu.addAction(self.actionExit)
        self.chooseTranslator.addAction(self.actionDeeplTranslator)
        self.chooseTranslator.addAction(self.actionGoogleTranslator)
        self.MenuTranslate.addAction(self.chooseTranslator.menuAction())
        self.MenuTranslate.addAction(self.actionLeaveTheFormatting)
        self.MenuType.addAction(self.actionPyttsx)
        self.MenuProunanciation.addAction(self.MenuType.menuAction())
        self.MenuBar.addAction(self.Menu.menuAction())
        self.MenuBar.addAction(self.MenuTranslate.menuAction())
        self.MenuBar.addAction(self.MenuProunanciation.menuAction())

        self.retranslateUi(MainWindow)
        self.DisplayArea.setCurrentIndex(0)
        self.cardWidget.setCurrentIndex(1)
        self.settingsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Translated mate"))
        self.TranslateWindow.setToolTip(_translate("MainWindow", "Translate text"))
        self.inputBox.setPlaceholderText(_translate("MainWindow", "Input text"))
        self.cleanTranslate.setToolTip(_translate("MainWindow", "Clean input and translated text"))
        self.reverseTranslate.setToolTip(_translate("MainWindow", "Reverse translate"))
        self.pronunciation.setToolTip(_translate("MainWindow", "Text pronunciation"))
        self.copyTranslate.setToolTip(_translate("MainWindow", "Copy translate to clipboard"))
        self.saveTranslatedText.setToolTip(_translate("MainWindow", "Save translated text"))
        self.pastSourceText.setToolTip(_translate("MainWindow", "Paste text from the clipboard for translate"))
        self.microphone.setToolTip(_translate("MainWindow", "Microphone input"))
        self.sourcePronunciation.setToolTip(_translate("MainWindow", "Text pronunciation"))
        self.sourceCopyTranslate.setToolTip(_translate("MainWindow", "Copy input text to clipboard"))
        self.charCounter.setText(_translate("MainWindow", "0 / 0 chars (0 words)"))
        self.prevTranslate.setToolTip(_translate("MainWindow", "Previous translate"))
        self.nextTranslate.setToolTip(_translate("MainWindow", "Next translate"))
        self.flashCardCansel.setToolTip(_translate("MainWindow", "Save translation window"))
        self.flashCardOk.setToolTip(_translate("MainWindow", "Save translation window"))
        self.defaultTranslatorLabel.setText(_translate("MainWindow", "Default translator:"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.generalTab), _translate("MainWindow", "General"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.translateTab), _translate("MainWindow", "Translate"))
        self.TranslationViewWindow.setToolTip(_translate("MainWindow", "Save translation window"))
        self.FlashCardsWindow.setToolTip(_translate("MainWindow", "Flash cards window"))
        self.SettingsWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Main setting window</p></body></html>"))
        self.Menu.setTitle(_translate("MainWindow", "Menu"))
        self.MenuTranslate.setTitle(_translate("MainWindow", "Translate"))
        self.chooseTranslator.setTitle(_translate("MainWindow", "Translator"))
        self.MenuProunanciation.setTitle(_translate("MainWindow", "Pronunciation"))
        self.MenuType.setTitle(_translate("MainWindow", "Type"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionGoogleTranslator.setText(_translate("MainWindow", "Google"))
        self.actionLeaveTheFormatting.setText(_translate("MainWindow", "Leave the formatting"))
        self.actionDeeplTranslator.setText(_translate("MainWindow", "Deepl"))
        self.actionPyttsx.setText(_translate("MainWindow", "Pyttsx"))
from ui.widgets.clickable_label import ClickableLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
