# Form implementation generated from reading ui file 'TranslateMate.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1090, 470)
        MainWindow.setMinimumSize(QtCore.QSize(1090, 470))
        MainWindow.setMaximumSize(QtCore.QSize(1090, 470))
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("* {\n"
"   background-color: #b8b6b6;\n"
"   font: Fira Sans Condensed;     \n"
"}\n"
"QScrollBar {\n"
"    border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #f4f4f5;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #d0d0d0;\n"
"    min-height: 0px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: -10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height:  -10 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.Grid = QtWidgets.QWidget(parent=MainWindow)
        self.Grid.setObjectName("Grid")
        self.TranslateWindow = ClickableLabel(parent=self.Grid)
        self.TranslateWindow.setGeometry(QtCore.QRect(10, 60, 40, 40))
        self.TranslateWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.TranslateWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.TranslateWindow.setAutoFillBackground(False)
        self.TranslateWindow.setStyleSheet("")
        self.TranslateWindow.setText("")
        self.TranslateWindow.setPixmap(QtGui.QPixmap("img/translation.png"))
        self.TranslateWindow.setScaledContents(True)
        self.TranslateWindow.setObjectName("TranslateWindow")
        self.DisplayArea = QtWidgets.QStackedWidget(parent=self.Grid)
        self.DisplayArea.setGeometry(QtCore.QRect(50, 0, 1031, 441))
        self.DisplayArea.setObjectName("DisplayArea")
        self.Translate = QtWidgets.QWidget()
        self.Translate.setObjectName("Translate")
        self.inputBox = QtWidgets.QTextEdit(parent=self.Translate)
        self.inputBox.setGeometry(QtCore.QRect(20, 50, 500, 380))
        self.inputBox.setStyleSheet("border: 1px solid black;\n"
"border-radius: 10px;\n"
"background: #f4f4f5;\n"
"font-size: 16px;\n"
"color:black;")
        self.inputBox.setObjectName("inputBox")
        self.translateBox = QtWidgets.QTextEdit(parent=self.Translate)
        self.translateBox.setEnabled(True)
        self.translateBox.setGeometry(QtCore.QRect(530, 50, 500, 380))
        self.translateBox.setStyleSheet("border: 1px solid black;\n"
"border-radius: 10px;\n"
"background: #f4f4f5;\n"
"font-size: 16px;\n"
"color:black;")
        self.translateBox.setReadOnly(True)
        self.translateBox.setObjectName("translateBox")
        self.copyTranslate = ClickableLabel(parent=self.Translate)
        self.copyTranslate.setGeometry(QtCore.QRect(970, 380, 30, 30))
        self.copyTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.copyTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.copyTranslate.setAutoFillBackground(False)
        self.copyTranslate.setStyleSheet("#copyTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    opacity: 0.5;\n"
"    background: none;\n"
"    padding: 7px;\n"
"}\n"
"#copyTranslate:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.copyTranslate.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.copyTranslate.setText("")
        self.copyTranslate.setPixmap(QtGui.QPixmap("img/copy.png"))
        self.copyTranslate.setScaledContents(True)
        self.copyTranslate.setObjectName("copyTranslate")
        self.cleanTranslate = ClickableLabel(parent=self.Translate)
        self.cleanTranslate.setGeometry(QtCore.QRect(470, 60, 30, 30))
        self.cleanTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cleanTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.cleanTranslate.setAutoFillBackground(False)
        self.cleanTranslate.setStyleSheet("#cleanTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    background: none;\n"
"    opacity: 0.5;\n"
"    padding: 7px;\n"
"}\n"
"#cleanTranslate:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.cleanTranslate.setText("")
        self.cleanTranslate.setPixmap(QtGui.QPixmap("img/close.png"))
        self.cleanTranslate.setScaledContents(True)
        self.cleanTranslate.setObjectName("cleanTranslate")
        self.fromLang = QtWidgets.QComboBox(parent=self.Translate)
        self.fromLang.setGeometry(QtCore.QRect(30, 10, 200, 30))
        self.fromLang.setStyleSheet("#fromLang {\n"
"    font: 11pt Fira Sans Condensed;     \n"
"    background-color: #2e2e2e;\n"
"    border-top: 0px solid #3e3e3e;\n"
"    border-left: 0px solid #3e3e3e;\n"
"    border-right: 0px solid #3e3e3e;\n"
"    border-bottom: 2px solid #3e3e3e;\n"
"    padding: 5%;\n"
"    max-height: 30px;\n"
"    min-width: 140px;\n"
"    color: white;\n"
"    selection-background-color: #5e5e5e;\n"
"    border-radius: 2px;\n"
"}\n"
"#fromLang:drop-down {\n"
"    border: none;\n"
"}\n"
"#fromLang:down-arrow {\n"
"    image: url(img/downButton.png);\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-width: 0px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#fromLang:pressed {\n"
"    position: relative;\n"
"    top: 1px; left: 1px;\n"
"}")
        self.fromLang.setEditable(True)
        self.fromLang.setObjectName("fromLang")
        self.reverseTranslate = ClickableLabel(parent=self.Translate)
        self.reverseTranslate.setGeometry(QtCore.QRect(510, 10, 30, 30))
        self.reverseTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reverseTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.reverseTranslate.setAutoFillBackground(False)
        self.reverseTranslate.setStyleSheet("#reverseTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"}\n"
"#reverseTranslate:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.reverseTranslate.setText("")
        self.reverseTranslate.setPixmap(QtGui.QPixmap("img/reverseTranslate.png"))
        self.reverseTranslate.setScaledContents(True)
        self.reverseTranslate.setObjectName("reverseTranslate")
        self.toLang = QtWidgets.QComboBox(parent=self.Translate)
        self.toLang.setGeometry(QtCore.QRect(820, 10, 200, 30))
        self.toLang.setStyleSheet("#toLang {\n"
"    font: 11pt Fira Sans Condensed;     \n"
"    background-color: #2e2e2e;\n"
"    border-top: 0px solid #3e3e3e;\n"
"    border-left: 0px solid #3e3e3e;\n"
"    border-right: 0px solid #3e3e3e;\n"
"    border-bottom: 2px solid #3e3e3e;\n"
"    padding: 5%;\n"
"    max-height: 30px;\n"
"    min-width: 140px;\n"
"    color: white;\n"
"    selection-background-color: #5e5e5e;\n"
"    border-radius: 2px;\n"
"}\n"
"#toLang:drop-down {\n"
"    border: none;\n"
"}\n"
"#toLang:down-arrow {\n"
"    image: url(img/downButton.png);\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-width: 0px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#toLang:pressed {\n"
"    position: relative;\n"
"    top: 1px; left: 1px;\n"
"}")
        self.toLang.setEditable(True)
        self.toLang.setObjectName("toLang")
        self.saveTranslatedText = ClickableLabel(parent=self.Translate)
        self.saveTranslatedText.setGeometry(QtCore.QRect(940, 380, 30, 30))
        self.saveTranslatedText.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.saveTranslatedText.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.saveTranslatedText.setAutoFillBackground(False)
        self.saveTranslatedText.setStyleSheet("#saveTranslatedText {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    opacity: 0.5;\n"
"    background: none;\n"
"    padding: 7px;\n"
"}\n"
"#saveTranslatedText:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.saveTranslatedText.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.saveTranslatedText.setText("")
        self.saveTranslatedText.setPixmap(QtGui.QPixmap("img/saveTranslatedText.png"))
        self.saveTranslatedText.setScaledContents(True)
        self.saveTranslatedText.setObjectName("saveTranslatedText")
        self.pronunciation = ClickableLabel(parent=self.Translate)
        self.pronunciation.setGeometry(QtCore.QRect(910, 380, 30, 30))
        self.pronunciation.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pronunciation.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pronunciation.setAutoFillBackground(False)
        self.pronunciation.setStyleSheet("#pronunciation {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    opacity: 0.5;\n"
"    background: none;\n"
"    padding: 7px;\n"
"}\n"
"#pronunciation:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.pronunciation.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.pronunciation.setText("")
        self.pronunciation.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.pronunciation.setPixmap(QtGui.QPixmap("img/pronunciation.png"))
        self.pronunciation.setScaledContents(True)
        self.pronunciation.setObjectName("pronunciation")
        self.DisplayArea.addWidget(self.Translate)
        self.TranslationView = QtWidgets.QWidget()
        self.TranslationView.setObjectName("TranslationView")
        self.TranslationTableWidget = QtWidgets.QTableView(parent=self.TranslationView)
        self.TranslationTableWidget.setGeometry(QtCore.QRect(20, 0, 1021, 441))
        self.TranslationTableWidget.setStyleSheet("QTableWidget {\n"
"    border: transparent;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background: #fff5e0;\n"
"    color: #000000;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QTableWidget::item:focus\n"
"{\n"
"   background-color: #b8b6b6; \n"
"    background: #b8b6b6;\n"
"   selection-background-color: #b8b6b6;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    border-radius: 3px;\n"
"    text-align: center;\n"
"    font-weight: bold;\n"
"    spacing: 1px;\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #676767;\n"
"    font-size:12px;\n"
"}")
        self.TranslationTableWidget.setObjectName("TranslationTableWidget")
        self.DisplayArea.addWidget(self.TranslationView)
        self.FlashCards = QtWidgets.QWidget()
        self.FlashCards.setObjectName("FlashCards")
        self.cardWidget = QtWidgets.QStackedWidget(parent=self.FlashCards)
        self.cardWidget.setGeometry(QtCore.QRect(40, 60, 200, 151))
        self.cardWidget.setObjectName("cardWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.cardTextObj = QtWidgets.QPlainTextEdit(parent=self.page)
        self.cardTextObj.setGeometry(QtCore.QRect(3, 10, 191, 141))
        self.cardTextObj.setPlainText("")
        self.cardTextObj.setObjectName("cardTextObj")
        self.cardWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.cardWidget.addWidget(self.page_2)
        self.flashCardCansel = QtWidgets.QLabel(parent=self.FlashCards)
        self.flashCardCansel.setGeometry(QtCore.QRect(90, 230, 40, 40))
        self.flashCardCansel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.flashCardCansel.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.flashCardCansel.setAutoFillBackground(False)
        self.flashCardCansel.setStyleSheet("#flashCardsWindow {\n"
"    background-repeat: no-repeat;\n"
"    border-radius:  5px;\n"
"}\n"
"#flashCardsWindow:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.flashCardCansel.setText("")
        self.flashCardCansel.setPixmap(QtGui.QPixmap("img/cansel.png"))
        self.flashCardCansel.setScaledContents(True)
        self.flashCardCansel.setObjectName("flashCardCansel")
        self.flashCardOk = QtWidgets.QLabel(parent=self.FlashCards)
        self.flashCardOk.setGeometry(QtCore.QRect(130, 230, 40, 40))
        self.flashCardOk.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.flashCardOk.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.flashCardOk.setAutoFillBackground(False)
        self.flashCardOk.setStyleSheet("#flashCardsWindow {\n"
"    background-repeat: no-repeat;\n"
"    border-radius:  5px;\n"
"}\n"
"#flashCardsWindow:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.flashCardOk.setText("")
        self.flashCardOk.setPixmap(QtGui.QPixmap("img/ok.png"))
        self.flashCardOk.setScaledContents(True)
        self.flashCardOk.setObjectName("flashCardOk")
        self.DisplayArea.addWidget(self.FlashCards)
        self.TranslationViewWindow = ClickableLabel(parent=self.Grid)
        self.TranslationViewWindow.setGeometry(QtCore.QRect(10, 110, 40, 40))
        self.TranslationViewWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.TranslationViewWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.TranslationViewWindow.setAutoFillBackground(False)
        self.TranslationViewWindow.setStyleSheet("")
        self.TranslationViewWindow.setText("")
        self.TranslationViewWindow.setPixmap(QtGui.QPixmap("img/saveButton.png"))
        self.TranslationViewWindow.setScaledContents(True)
        self.TranslationViewWindow.setObjectName("TranslationViewWindow")
        self.FlashCardsWindow = ClickableLabel(parent=self.Grid)
        self.FlashCardsWindow.setGeometry(QtCore.QRect(10, 160, 40, 40))
        self.FlashCardsWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.FlashCardsWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.FlashCardsWindow.setAutoFillBackground(False)
        self.FlashCardsWindow.setStyleSheet("")
        self.FlashCardsWindow.setText("")
        self.FlashCardsWindow.setPixmap(QtGui.QPixmap("img/flashCards.png"))
        self.FlashCardsWindow.setScaledContents(True)
        self.FlashCardsWindow.setObjectName("FlashCardsWindow")
        MainWindow.setCentralWidget(self.Grid)
        self.MenuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 1090, 20))
        self.MenuBar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.MenuBar.setAutoFillBackground(False)
        self.MenuBar.setStyleSheet("#MenuBar {\n"
"    background: black;\n"
"    color: white;\n"
"}\n"
"")
        self.MenuBar.setObjectName("MenuBar")
        self.Menu = QtWidgets.QMenu(parent=self.MenuBar)
        self.Menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Menu.setStyleSheet("background-color: #2e2e2e;")
        self.Menu.setObjectName("Menu")
        self.MenuTranslate = QtWidgets.QMenu(parent=self.MenuBar)
        self.MenuTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MenuTranslate.setStyleSheet("background-color: #2e2e2e;")
        self.MenuTranslate.setObjectName("MenuTranslate")
        self.chooseTranslator = QtWidgets.QMenu(parent=self.MenuTranslate)
        self.chooseTranslator.setStyleSheet("")
        self.chooseTranslator.setObjectName("chooseTranslator")
        self.MenuProunanciation = QtWidgets.QMenu(parent=self.MenuBar)
        self.MenuProunanciation.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MenuProunanciation.setStyleSheet("background-color: #2e2e2e;")
        self.MenuProunanciation.setObjectName("MenuProunanciation")
        self.MenuType = QtWidgets.QMenu(parent=self.MenuProunanciation)
        self.MenuType.setObjectName("MenuType")
        MainWindow.setMenuBar(self.MenuBar)
        self.StatusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.StatusBar.setObjectName("StatusBar")
        MainWindow.setStatusBar(self.StatusBar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setShortcutVisibleInContextMenu(False)
        self.actionExit.setObjectName("actionExit")
        self.actionGoogleTranslator = QtGui.QAction(parent=MainWindow)
        self.actionGoogleTranslator.setCheckable(True)
        self.actionGoogleTranslator.setChecked(True)
        self.actionGoogleTranslator.setObjectName("actionGoogleTranslator")
        self.actionLeaveTheFormatting = QtGui.QAction(parent=MainWindow)
        self.actionLeaveTheFormatting.setCheckable(True)
        self.actionLeaveTheFormatting.setObjectName("actionLeaveTheFormatting")
        self.actionDeeplTranslator = QtGui.QAction(parent=MainWindow)
        self.actionDeeplTranslator.setCheckable(True)
        self.actionDeeplTranslator.setChecked(False)
        self.actionDeeplTranslator.setObjectName("actionDeeplTranslator")
        self.actionPyttsx = QtGui.QAction(parent=MainWindow)
        self.actionPyttsx.setCheckable(True)
        self.actionPyttsx.setChecked(True)
        self.actionPyttsx.setObjectName("actionPyttsx")
        self.Menu.addAction(self.actionExit)
        self.chooseTranslator.addAction(self.actionDeeplTranslator)
        self.chooseTranslator.addAction(self.actionGoogleTranslator)
        self.MenuTranslate.addAction(self.chooseTranslator.menuAction())
        self.MenuTranslate.addAction(self.actionLeaveTheFormatting)
        self.MenuType.addAction(self.actionPyttsx)
        self.MenuProunanciation.addAction(self.MenuType.menuAction())
        self.MenuBar.addAction(self.Menu.menuAction())
        self.MenuBar.addAction(self.MenuTranslate.menuAction())
        self.MenuBar.addAction(self.MenuProunanciation.menuAction())

        self.retranslateUi(MainWindow)
        self.DisplayArea.setCurrentIndex(0)
        self.cardWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Translated mate"))
        self.TranslateWindow.setToolTip(_translate("MainWindow", "Translate text"))
        self.inputBox.setPlaceholderText(_translate("MainWindow", "Input text"))
        self.copyTranslate.setToolTip(_translate("MainWindow", "Copy translate to clipboard"))
        self.cleanTranslate.setToolTip(_translate("MainWindow", "Clean input and translated text"))
        self.reverseTranslate.setToolTip(_translate("MainWindow", "Reverse translate"))
        self.saveTranslatedText.setToolTip(_translate("MainWindow", "Save translated text"))
        self.pronunciation.setToolTip(_translate("MainWindow", "Pronunciation"))
        self.flashCardCansel.setToolTip(_translate("MainWindow", "Save translation window"))
        self.flashCardOk.setToolTip(_translate("MainWindow", "Save translation window"))
        self.TranslationViewWindow.setToolTip(_translate("MainWindow", "Save translation window"))
        self.FlashCardsWindow.setToolTip(_translate("MainWindow", "Flash cards window"))
        self.Menu.setTitle(_translate("MainWindow", "Menu"))
        self.MenuTranslate.setTitle(_translate("MainWindow", "Translate"))
        self.chooseTranslator.setTitle(_translate("MainWindow", "Translator"))
        self.MenuProunanciation.setTitle(_translate("MainWindow", "Pronunciation"))
        self.MenuType.setTitle(_translate("MainWindow", "Type"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionGoogleTranslator.setText(_translate("MainWindow", "Google"))
        self.actionLeaveTheFormatting.setText(_translate("MainWindow", "Leave the formatting"))
        self.actionDeeplTranslator.setText(_translate("MainWindow", "Deepl"))
        self.actionPyttsx.setText(_translate("MainWindow", "Pyttsx"))
from ui.widgets.clickable_label import ClickableLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
